const TANK_RELOAD   = 3
const TANK_ACCEL    = 48 //32
const TANK_DECEL    = 0.9
const TANK_MAXSPEED = 64 //32
const TANK_BOUNCE   = 6
const TANK_HEALTH   = 100
const TANK_TURN     = 0.3
const TURRET_TURN   = 1
const CANNON_DAMAGE = 34
const CANNON_SPEED  = 20
const ROCKS         = 20
const TARGET_FPS    = 40
